/**
 * Job Notification Tracker — Realistic Indian Tech Jobs Dataset
 * 60 jobs with varied roles, companies, locations, and details.
 */

const JOBS_DATA = [
  {
    id: 1,
    title: "SDE Intern",
    company: "Amazon",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Python", "Data Structures", "Algorithms"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.amazon.jobs/en/jobs/123456",
    description: "Join Amazon's internship program to work on scalable systems. Learn from experienced engineers and contribute to real-world projects. Ideal for students passionate about software development."
  },
  {
    id: 2,
    title: "Graduate Engineer Trainee",
    company: "TCS",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "SQL", "Spring Boot", "Angular"],
    source: "Naukri",
    postedDaysAgo: 5,
    salaryRange: "3–5 LPA",
    applyUrl: "https://careers.tcs.com/job/12345",
    description: "TCS is hiring fresh graduates for their GET program. Comprehensive training provided. Work on enterprise applications and gain exposure to various technologies. Great opportunity for career growth."
  },
  {
    id: 3,
    title: "Junior Backend Developer",
    company: "Razorpay",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Node.js", "MongoDB", "Redis", "AWS"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "6–10 LPA",
    applyUrl: "https://razorpay.com/careers/job/123",
    description: "Build scalable payment infrastructure at Razorpay. Work with microservices architecture and handle high transaction volumes. Fast-paced startup environment with learning opportunities."
  },
  {
    id: 4,
    title: "Frontend Intern",
    company: "Flipkart",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["React", "JavaScript", "HTML", "CSS"],
    source: "Indeed",
    postedDaysAgo: 3,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://flipkartcareers.com/intern/123",
    description: "Internship opportunity at Flipkart to work on frontend features. Build user interfaces for millions of users. Mentorship from senior developers and exposure to modern web technologies."
  },
  {
    id: 5,
    title: "QA Intern",
    company: "Infosys",
    location: "Pune",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Manual Testing", "Selenium", "Java", "TestNG"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://career.infosys.com/job/123",
    description: "Join Infosys QA team as an intern. Learn automation testing and work on enterprise projects. Structured training program with certification opportunities. Perfect for freshers."
  },
  {
    id: 6,
    title: "Data Analyst Intern",
    company: "Swiggy",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "SQL", "Excel", "Tableau"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://careers.swiggy.com/intern/123",
    description: "Analyze food delivery data at Swiggy. Work with large datasets and create insights. Learn data visualization and statistical analysis. Great for students interested in data science."
  },
  {
    id: 7,
    title: "Java Developer (0-1)",
    company: "Wipro",
    location: "Hyderabad",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java", "Spring", "Hibernate", "MySQL"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "3–5 LPA",
    applyUrl: "https://careers.wipro.com/job/123",
    description: "Wipro is looking for Java developers with 0-1 years experience. Work on enterprise Java applications. Training provided on Spring framework and microservices. Stable career opportunity."
  },
  {
    id: 8,
    title: "Python Developer (Fresher)",
    company: "Zoho",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Python", "Django", "PostgreSQL", "REST APIs"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "3–5 LPA",
    applyUrl: "https://careers.zoho.com/job/123",
    description: "Zoho is hiring freshers for Python development. Build SaaS products used by millions. Excellent work culture and learning environment. Chennai office with great facilities."
  },
  {
    id: 9,
    title: "React Developer (1-3)",
    company: "PhonePe",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "TypeScript", "Redux", "Jest"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "10–18 LPA",
    applyUrl: "https://phonepe.com/careers/job/123",
    description: "Build fintech products at PhonePe using React. Work on high-traffic applications handling millions of transactions. Modern tech stack and competitive compensation. Fast-growing company."
  },
  {
    id: 10,
    title: "Full Stack Developer",
    company: "CRED",
    location: "Bangalore",
    mode: "Remote",
    experience: "1-3",
    skills: ["React", "Node.js", "MongoDB", "AWS"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "10–18 LPA",
    applyUrl: "https://cred.club/careers/job/123",
    description: "Join CRED's engineering team to build premium fintech products. Work on both frontend and backend. Startup culture with equity options. Remote-first company with flexible hours."
  },
  {
    id: 11,
    title: "Backend Engineer",
    company: "Juspay",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Java", "Go", "PostgreSQL", "Kafka"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "10–18 LPA",
    applyUrl: "https://juspay.in/careers/job/123",
    description: "Build payment infrastructure at Juspay. Work on high-performance systems processing millions of transactions. Learn distributed systems and microservices. Great engineering culture."
  },
  {
    id: 12,
    title: "DevOps Engineer",
    company: "Accenture",
    location: "Mumbai",
    mode: "Onsite",
    experience: "1-3",
    skills: ["Docker", "Kubernetes", "AWS", "Jenkins"],
    source: "Naukri",
    postedDaysAgo: 8,
    salaryRange: "6–10 LPA",
    applyUrl: "https://accenture.com/careers/job/123",
    description: "Manage cloud infrastructure at Accenture. Work with Docker, Kubernetes, and CI/CD pipelines. Support multiple client projects. Good learning opportunities and certifications."
  },
  {
    id: 13,
    title: "Mobile Developer (React Native)",
    company: "Paytm",
    location: "Noida",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React Native", "JavaScript", "Redux", "Firebase"],
    source: "Indeed",
    postedDaysAgo: 5,
    salaryRange: "6–10 LPA",
    applyUrl: "https://paytm.com/careers/job/123",
    description: "Build mobile apps at Paytm using React Native. Work on features used by millions of users. Cross-platform development experience. Fast-paced fintech environment."
  },
  {
    id: 14,
    title: "Data Engineer",
    company: "Capgemini",
    location: "Pune",
    mode: "Onsite",
    experience: "1-3",
    skills: ["Python", "Spark", "Hadoop", "SQL"],
    source: "Naukri",
    postedDaysAgo: 9,
    salaryRange: "6–10 LPA",
    applyUrl: "https://capgemini.com/careers/job/123",
    description: "Work on data pipelines at Capgemini. Build ETL processes and data warehouses. Learn big data technologies. Stable company with good work-life balance."
  },
  {
    id: 15,
    title: "UI/UX Designer",
    company: "Freshworks",
    location: "Chennai",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Figma", "Adobe XD", "Prototyping", "User Research"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "6–10 LPA",
    applyUrl: "https://freshworks.com/careers/job/123",
    description: "Design SaaS products at Freshworks. Work on user interfaces for B2B software. Collaborate with product and engineering teams. Great design culture and mentorship."
  },
  {
    id: 16,
    title: "SDE Intern",
    company: "Microsoft",
    location: "Hyderabad",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["C#", ".NET", "Azure", "SQL Server"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://careers.microsoft.com/intern/123",
    description: "Microsoft internship program in Hyderabad. Work on cloud services and enterprise software. Learn from industry experts. Excellent internship experience with potential for full-time offer."
  },
  {
    id: 17,
    title: "Backend Developer",
    company: "Ola",
    location: "Bangalore",
    mode: "Remote",
    experience: "0-1",
    skills: ["Node.js", "MongoDB", "Redis", "Microservices"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "6–10 LPA",
    applyUrl: "https://olacabs.com/careers/job/123",
    description: "Build backend services for Ola's ride-sharing platform. Work on high-scale systems. Learn microservices architecture. Startup environment with good growth opportunities."
  },
  {
    id: 18,
    title: "Frontend Developer",
    company: "Myntra",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["React", "JavaScript", "CSS", "Redux"],
    source: "Indeed",
    postedDaysAgo: 6,
    salaryRange: "6–10 LPA",
    applyUrl: "https://myntra.com/careers/job/123",
    description: "Build e-commerce frontend at Myntra. Work on shopping experience for millions of users. Modern React stack. Great learning environment and competitive salary."
  },
  {
    id: 19,
    title: "QA Engineer",
    company: "Cognizant",
    location: "Chennai",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Selenium", "Java", "TestNG", "API Testing"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "3–5 LPA",
    applyUrl: "https://cognizant.com/careers/job/123",
    description: "Join Cognizant's QA team. Work on automation testing for enterprise clients. Learn testing frameworks and tools. Good training program and career growth path."
  },
  {
    id: 20,
    title: "Data Scientist Intern",
    company: "IBM",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "Machine Learning", "SQL", "Statistics"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://ibm.com/careers/intern/123",
    description: "IBM internship in data science. Work on AI/ML projects. Learn from data scientists. Exposure to enterprise AI solutions. Great for students interested in ML."
  },
  {
    id: 21,
    title: "Full Stack Developer",
    company: "Oracle",
    location: "Bangalore",
    mode: "Onsite",
    experience: "1-3",
    skills: ["Java", "JavaScript", "Oracle DB", "Spring"],
    source: "Naukri",
    postedDaysAgo: 10,
    salaryRange: "10–18 LPA",
    applyUrl: "https://oracle.com/careers/job/123",
    description: "Build enterprise applications at Oracle. Work with Java and Oracle databases. Learn enterprise architecture. Stable company with good benefits and work culture."
  },
  {
    id: 22,
    title: "React Developer",
    company: "Dell",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "TypeScript", "GraphQL", "Jest"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "10–18 LPA",
    applyUrl: "https://dell.com/careers/job/123",
    description: "Build internal tools and dashboards at Dell using React. Work on modern web applications. Good work-life balance. Multinational company with global exposure."
  },
  {
    id: 23,
    title: "Backend Engineer",
    company: "SAP",
    location: "Bangalore",
    mode: "Onsite",
    experience: "1-3",
    skills: ["Java", "SAP HANA", "Spring", "Microservices"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "10–18 LPA",
    applyUrl: "https://sap.com/careers/job/123",
    description: "Develop SAP solutions and enterprise software. Work with SAP technologies and cloud platforms. Learn enterprise software development. Excellent benefits and career growth."
  },
  {
    id: 24,
    title: "SDE Intern",
    company: "Google",
    location: "Hyderabad",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["C++", "Python", "Algorithms", "Data Structures"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://careers.google.com/intern/123",
    description: "Google internship program. Work on impactful projects. Learn from world-class engineers. Competitive internship with excellent learning opportunities. Highly selective program."
  },
  {
    id: 25,
    title: "Frontend Developer",
    company: "Uber",
    location: "Bangalore",
    mode: "Remote",
    experience: "1-3",
    skills: ["React", "TypeScript", "GraphQL", "Webpack"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "10–18 LPA",
    applyUrl: "https://uber.com/careers/job/123",
    description: "Build rider and driver apps at Uber. Work on high-scale frontend applications. Modern React stack. Global company with excellent engineering culture."
  },
  {
    id: 26,
    title: "Python Developer",
    company: "ThoughtWorks",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Python", "Django", "PostgreSQL", "TDD"],
    source: "LinkedIn",
    postedDaysAgo: 5,
    salaryRange: "10–18 LPA",
    applyUrl: "https://thoughtworks.com/careers/job/123",
    description: "Work on client projects at ThoughtWorks. Practice agile methodologies and TDD. Great learning culture. Work with diverse technologies and clients."
  },
  {
    id: 27,
    title: "Java Developer",
    company: "Atlassian",
    location: "Bangalore",
    mode: "Remote",
    experience: "1-3",
    skills: ["Java", "Spring Boot", "AWS", "Microservices"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "10–18 LPA",
    applyUrl: "https://atlassian.com/careers/job/123",
    description: "Build developer tools at Atlassian. Work on Jira, Confluence, and other products. Remote-first culture. Great engineering practices and work-life balance."
  },
  {
    id: 28,
    title: "Full Stack Developer",
    company: "Razorpay",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["React", "Node.js", "PostgreSQL", "Redis"],
    source: "LinkedIn",
    postedDaysAgo: 6,
    salaryRange: "6–10 LPA",
    applyUrl: "https://razorpay.com/careers/job/456",
    description: "Build payment products at Razorpay. Full stack development opportunity. Learn fintech domain. Fast-growing startup with excellent culture."
  },
  {
    id: 29,
    title: "DevOps Engineer",
    company: "Swiggy",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Kubernetes", "Docker", "AWS", "Terraform"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "10–18 LPA",
    applyUrl: "https://careers.swiggy.com/job/123",
    description: "Manage infrastructure at Swiggy. Work on cloud platforms and CI/CD. Support high-traffic food delivery platform. Learn modern DevOps practices."
  },
  {
    id: 30,
    title: "Data Analyst",
    company: "Zomato",
    location: "Gurgaon",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Python", "SQL", "Tableau", "Excel"],
    source: "Indeed",
    postedDaysAgo: 7,
    salaryRange: "6–10 LPA",
    applyUrl: "https://zomato.com/careers/job/123",
    description: "Analyze food delivery data at Zomato. Create insights for business decisions. Work with large datasets. Fast-paced startup environment."
  },
  {
    id: 31,
    title: "React Developer",
    company: "Meesho",
    location: "Bangalore",
    mode: "Remote",
    experience: "1-3",
    skills: ["React", "TypeScript", "Redux", "Next.js"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "10–18 LPA",
    applyUrl: "https://meesho.com/careers/job/123",
    description: "Build e-commerce platform at Meesho. Work on social commerce features. Modern React stack. High-growth startup with equity options."
  },
  {
    id: 32,
    title: "Backend Developer",
    company: "ShareChat",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Java", "Spring Boot", "MongoDB", "Kafka"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "10–18 LPA",
    applyUrl: "https://sharechat.com/careers/job/123",
    description: "Build social media backend at ShareChat. Work on high-scale systems. Learn distributed systems. Fast-growing social media company."
  },
  {
    id: 33,
    title: "SDE Intern",
    company: "Intuit",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Spring", "React", "SQL"],
    source: "LinkedIn",
    postedDaysAgo: 5,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://intuit.com/careers/intern/123",
    description: "Intuit internship in Bangalore. Work on financial software products. Learn full stack development. Great mentorship and learning opportunities."
  },
  {
    id: 34,
    title: "Frontend Developer",
    company: "MakeMyTrip",
    location: "Gurgaon",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["React", "JavaScript", "CSS", "Redux"],
    source: "Naukri",
    postedDaysAgo: 8,
    salaryRange: "6–10 LPA",
    applyUrl: "https://makemytrip.com/careers/job/123",
    description: "Build travel booking platform at MakeMyTrip. Work on user interfaces. Learn e-commerce frontend development. Established company with good benefits."
  },
  {
    id: 35,
    title: "Python Developer",
    company: "OYO",
    location: "Gurgaon",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Python", "Django", "PostgreSQL", "Redis"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "10–18 LPA",
    applyUrl: "https://oyo.com/careers/job/123",
    description: "Build hotel booking platform at OYO. Work on backend services. Learn hospitality tech. Fast-growing company with global presence."
  },
  {
    id: 36,
    title: "Full Stack Developer",
    company: "Byju's",
    location: "Bangalore",
    mode: "Remote",
    experience: "1-3",
    skills: ["React", "Node.js", "MongoDB", "AWS"],
    source: "LinkedIn",
    postedDaysAgo: 6,
    salaryRange: "10–18 LPA",
    applyUrl: "https://byjus.com/careers/job/123",
    description: "Build edtech platform at Byju's. Work on learning management systems. Full stack development. Edtech leader with innovative products."
  },
  {
    id: 37,
    title: "Backend Engineer",
    company: "Unacademy",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Java", "Spring Boot", "PostgreSQL", "Redis"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "10–18 LPA",
    applyUrl: "https://unacademy.com/careers/job/123",
    description: "Build education platform backend at Unacademy. Work on video streaming and live classes. Learn scalable backend systems. Edtech startup with good culture."
  },
  {
    id: 38,
    title: "React Developer",
    company: "Vedantu",
    location: "Bangalore",
    mode: "Remote",
    experience: "0-1",
    skills: ["React", "JavaScript", "Redux", "WebRTC"],
    source: "Indeed",
    postedDaysAgo: 9,
    salaryRange: "6–10 LPA",
    applyUrl: "https://vedantu.com/careers/job/123",
    description: "Build online tutoring platform at Vedantu. Work on interactive learning features. Learn React and real-time communication. Growing edtech company."
  },
  {
    id: 39,
    title: "SDE Intern",
    company: "Groww",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["React", "Node.js", "MongoDB", "JavaScript"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://groww.in/careers/intern/123",
    description: "Groww internship in fintech. Build investment platform features. Learn full stack development. Fast-growing fintech startup with great learning culture."
  },
  {
    id: 40,
    title: "Backend Developer",
    company: "Upstox",
    location: "Mumbai",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Java", "Spring Boot", "Kafka", "PostgreSQL"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "10–18 LPA",
    applyUrl: "https://upstox.com/careers/job/123",
    description: "Build trading platform backend at Upstox. Work on high-frequency trading systems. Learn fintech backend development. Growing stock trading platform."
  },
  {
    id: 41,
    title: "Frontend Developer",
    company: "Nykaa",
    location: "Mumbai",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "TypeScript", "Redux", "Next.js"],
    source: "LinkedIn",
    postedDaysAgo: 5,
    salaryRange: "10–18 LPA",
    applyUrl: "https://nykaa.com/careers/job/123",
    description: "Build beauty e-commerce platform at Nykaa. Work on shopping experience. Modern React stack. Leading beauty e-commerce company."
  },
  {
    id: 42,
    title: "Full Stack Developer",
    company: "Lenskart",
    location: "Gurgaon",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "Node.js", "MongoDB", "AWS"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "10–18 LPA",
    applyUrl: "https://lenskart.com/careers/job/123",
    description: "Build eyewear e-commerce platform at Lenskart. Work on AR try-on features. Full stack development. Innovative e-commerce company."
  },
  {
    id: 43,
    title: "Python Developer",
    company: "Dream11",
    location: "Mumbai",
    mode: "Remote",
    experience: "1-3",
    skills: ["Python", "Django", "PostgreSQL", "Redis"],
    source: "LinkedIn",
    postedDaysAgo: 7,
    salaryRange: "10–18 LPA",
    applyUrl: "https://dream11.com/careers/job/123",
    description: "Build fantasy sports platform at Dream11. Work on backend services. Learn high-scale systems. Leading fantasy sports platform."
  },
  {
    id: 44,
    title: "React Developer",
    company: "PolicyBazaar",
    location: "Gurgaon",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["React", "JavaScript", "Redux", "CSS"],
    source: "Naukri",
    postedDaysAgo: 8,
    salaryRange: "6–10 LPA",
    applyUrl: "https://policybazaar.com/careers/job/123",
    description: "Build insurance platform at PolicyBazaar. Work on frontend features. Learn fintech domain. Leading insurance aggregator."
  },
  {
    id: 45,
    title: "Backend Engineer",
    company: "CarDekho",
    location: "Gurgaon",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Java", "Spring Boot", "MongoDB", "Elasticsearch"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "10–18 LPA",
    applyUrl: "https://cardekho.com/careers/job/123",
    description: "Build automotive platform backend at CarDekho. Work on search and recommendation systems. Learn e-commerce backend. Leading auto portal."
  },
  {
    id: 46,
    title: "SDE Intern",
    company: "Cure.fit",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["React", "Node.js", "MongoDB", "JavaScript"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://cure.fit/careers/intern/123",
    description: "Cure.fit internship in healthtech. Build fitness and wellness platform. Learn full stack development. Healthtech startup with innovative products."
  },
  {
    id: 47,
    title: "Full Stack Developer",
    company: "NoBroker",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "Node.js", "PostgreSQL", "AWS"],
    source: "LinkedIn",
    postedDaysAgo: 6,
    salaryRange: "10–18 LPA",
    applyUrl: "https://nobroker.in/careers/job/123",
    description: "Build real estate platform at NoBroker. Work on property search and booking. Full stack development. Leading proptech company."
  },
  {
    id: 48,
    title: "Backend Developer",
    company: "BigBasket",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Java", "Spring Boot", "MySQL", "Kafka"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "10–18 LPA",
    applyUrl: "https://bigbasket.com/careers/job/123",
    description: "Build grocery delivery platform at BigBasket. Work on order management systems. Learn e-commerce backend. Leading online grocery platform."
  },
  {
    id: 49,
    title: "React Developer",
    company: "Urban Company",
    location: "Gurgaon",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "TypeScript", "Redux", "PWA"],
    source: "LinkedIn",
    postedDaysAgo: 5,
    salaryRange: "10–18 LPA",
    applyUrl: "https://urbancompany.com/careers/job/123",
    description: "Build home services platform at Urban Company. Work on booking and scheduling features. Modern React stack. Leading home services platform."
  },
  {
    id: 50,
    title: "Python Developer",
    company: "Practo",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Python", "Django", "PostgreSQL", "Redis"],
    source: "LinkedIn",
    postedDaysAgo: 7,
    salaryRange: "10–18 LPA",
    applyUrl: "https://practo.com/careers/job/123",
    description: "Build healthcare platform at Practo. Work on doctor booking and telemedicine. Learn healthtech domain. Leading healthcare platform."
  },
  {
    id: 51,
    title: "Frontend Developer",
    company: "1mg",
    location: "Gurgaon",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["React", "JavaScript", "Redux", "CSS"],
    source: "Indeed",
    postedDaysAgo: 9,
    salaryRange: "6–10 LPA",
    applyUrl: "https://1mg.com/careers/job/123",
    description: "Build pharmacy platform at 1mg. Work on medicine ordering features. Learn e-commerce frontend. Leading online pharmacy."
  },
  {
    id: 52,
    title: "Backend Engineer",
    company: "Rapido",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Java", "Spring Boot", "MongoDB", "Redis"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "10–18 LPA",
    applyUrl: "https://rapido.bike/careers/job/123",
    description: "Build bike taxi platform backend at Rapido. Work on ride booking systems. Learn mobility tech. Fast-growing bike taxi platform."
  },
  {
    id: 53,
    title: "Full Stack Developer",
    company: "BharatPe",
    location: "Delhi",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "Node.js", "PostgreSQL", "AWS"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "10–18 LPA",
    applyUrl: "https://bharatpe.com/careers/job/123",
    description: "Build fintech platform at BharatPe. Work on payment solutions. Full stack development. Leading fintech startup."
  },
  {
    id: 54,
    title: "React Developer",
    company: "Khatabook",
    location: "Bangalore",
    mode: "Remote",
    experience: "1-3",
    skills: ["React", "TypeScript", "Redux", "PWA"],
    source: "LinkedIn",
    postedDaysAgo: 6,
    salaryRange: "10–18 LPA",
    applyUrl: "https://khatabook.com/careers/job/123",
    description: "Build accounting platform at Khatabook. Work on business management features. Modern React stack. Leading fintech for small businesses."
  },
  {
    id: 55,
    title: "SDE Intern",
    company: "Mobikwik",
    location: "Gurgaon",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Spring", "React", "MySQL"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://mobikwik.com/careers/intern/123",
    description: "Mobikwik internship in fintech. Build payment platform features. Learn full stack development. Established fintech company."
  },
  {
    id: 56,
    title: "Backend Developer",
    company: "InMobi",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Java", "Spring Boot", "Cassandra", "Kafka"],
    source: "LinkedIn",
    postedDaysAgo: 8,
    salaryRange: "10–18 LPA",
    applyUrl: "https://inmobi.com/careers/job/123",
    description: "Build ad tech platform backend at InMobi. Work on high-scale ad serving systems. Learn ad tech domain. Leading mobile advertising platform."
  },
  {
    id: 57,
    title: "Python Developer",
    company: "Quikr",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Python", "Django", "PostgreSQL", "Elasticsearch"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "10–18 LPA",
    applyUrl: "https://quikr.com/careers/job/123",
    description: "Build classifieds platform at Quikr. Work on search and listing features. Learn marketplace backend. Leading classifieds platform."
  },
  {
    id: 58,
    title: "Full Stack Developer",
    company: "RedBus",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "Node.js", "MongoDB", "AWS"],
    source: "LinkedIn",
    postedDaysAgo: 5,
    salaryRange: "10–18 LPA",
    applyUrl: "https://redbus.in/careers/job/123",
    description: "Build bus booking platform at RedBus. Work on booking and payment features. Full stack development. Leading bus booking platform."
  },
  {
    id: 59,
    title: "React Developer",
    company: "Cleartrip",
    location: "Mumbai",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["React", "JavaScript", "Redux", "CSS"],
    source: "Naukri",
    postedDaysAgo: 10,
    salaryRange: "6–10 LPA",
    applyUrl: "https://cleartrip.com/careers/job/123",
    description: "Build travel booking platform at Cleartrip. Work on flight and hotel booking. Learn travel tech. Established travel booking company."
  },
  {
    id: 60,
    title: "Backend Engineer",
    company: "Ixigo",
    location: "Gurgaon",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Java", "Spring Boot", "PostgreSQL", "Redis"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "10–18 LPA",
    applyUrl: "https://ixigo.com/careers/job/123",
    description: "Build travel platform backend at Ixigo. Work on search and booking systems. Learn travel tech backend. Fast-growing travel platform."
  }
];
